### ISSUE TITLE
Create an blank issue template for catalog data entry

### ISSUE THREAD

**Issue by slucey** [NOAA-EDAB/catalog#10]
As an alternative to filling out the google form to populate the catalog entry, we will provide a blank template that can be filled out on GitHub.

**Comment by slucey** [comment]
Need to make sure that blank is renamed prior to being filled out.

Will then use a pull request to incorporate.

**Comment by slucey** [comment]
@andybeet has an example to do this using an issue template

**Comment by andybeet** [comment]
Here is an example of an issue [template](https://github.com/NEFSC/NEFSC-Spatial/issues/new?assignees=&labels=enhancement&projects=&template=submit-new-data.yml&title=%5BRequest%5D%3A+)

Here is a link to the [code](https://github.com/NEFSC/NEFSC-Spatial/blob/main/.github/ISSUE_TEMPLATE/submit-new-data.yml?plain=1) that generates the template
