### ISSUE TITLE
Phytoplankton size class plots

### ISSUE THREAD

**Issue by khyde** [NOAA-EDAB/catalog#112]
Can you confirm that the plots on the [PSC catalog page](https://noaa-edab.github.io/catalog/phytoplankton-size-class.html) are 2023.  The current catalog plots look almost identical to what was in last year's reports and don't line up with the expected 2023 data.

**Comment by khyde** [comment]
FMICRO is the fraction of microplankton and MICRO is the concentration.  FMICRO is correct for these plots.  
Apologies for any confusion.  I thought there were data descriptions in the files themselves.  I will work to update those for the future.

**Comment by BBeltz1** [comment]
Okay, good to know. Catalog is correctly plotting the data _currently in ecodata_. I have verified that the datafiles being used in ecodata are exactly identical to the FMICRO, FNANO and FPICO datafiles in your repo. So as far as I can tell, there are no obvious issues in ecodata that could be causing these issues. I will continue scanning the data to make sure things on my end are correct. If you could double check your processing, or even plot your data files locally to verify, that would be helpful.

**Comment by khyde** [comment]
Here is my version of the 2023 plot (I created it awhile ago so it doesn't include the last couple of months). The GOM green line should be way above the climatology. Can you confirm that the dates you are plotting are 2023? 
![W_2023-NES_EPU_NOESTUARIES-PHYTOSIZE-CLIMATOLOGY](https://github.com/NOAA-EDAB/catalog/assets/5922605/70063663-4fab-49bb-ab31-6ad9a7b7f4c8)

**Comment by BBeltz1** [comment]
Thanks for clarifying. Since your plots are looking good, I suspect there is an issue with the plotting code in ecodata. I didn't write that code, so I will track it down and diagnose the issue. May take me a minute since it isn't mine, but hopefully the issue is obvious. Thanks for pointing this out and thanks for your patience while I sort this out.

**Comment by khyde** [comment]
https://github.com/khyde/READ-EDAB-SOE-PHYTOPLANKTON/tree/main/V2024/DATA_EXTRACTS/SOE_FORMAT

**Comment by khyde** [comment]
Here is my latest 2023 PSC [PSC updated with OC-CCI data through 2023](https://github.com/khyde/READ-EDAB-SOE-PHYTOPLANKTON/tree/main/V2024/DATA_EXTRACTS/SOE_FORMAT) plot.  It is definitely different than what you are showing on the catalog page. 

![W_2023-NES_EPU_NOESTUARIES-PHYTOSIZE-CLIMATOLOGY](https://github.com/NOAA-EDAB/catalog/assets/5922605/8ff5bc64-ce21-49da-af40-759bd9f7740b)

**Comment by khyde** [comment]
I uploaded new MICRO, NANO and PICO data here.  I removed the F files, instead the fractions will need to be calculated manually (so that they add up to 1).  

For the 2023 lines:
2023 Total = 2023 Micro + 2023 Nano + 2023 Pico (median)
FMicro = Micro/Total
FNano = Nano/Total

For the shaded polygons:
Climatology Total = WEEK Micro + WEEK Nano + WEEK Pico (median)
Clim FMicro = WEEK Micro/Clim Total
Clim FNano = WEEK Nano/Clim Total
Clim FPico = WEEK Pico/Clim Total

Here is my plot using the above calculations.
![W_2023-NES_EPU_NOESTUARIES-PHYTOSIZE-CLIMATOLOGY](https://github.com/NOAA-EDAB/catalog/assets/5922605/2dde7fc1-e359-4910-8444-c56c7ebd8018)
