### ISSUE TITLE
Various backend fixes

### ISSUE THREAD

**Issue by BBeltz1** [NOAA-EDAB/catalog#114]
The following issues were identified and need fixing:

- [ ] Aggregate Survey Biomass - unrendered table code chunks
- [x] Gulf Stream Index - incorrect plot behavior for New England
- [x] Harmful Algal Blooms - incorrect plot behavior for Mid Atlantic
- [ ]

**Comment by andybeet** [comment]
for  `plot_gsi` - i think returning text "This indicator is only present in the `MidAtlantic` report" is consistent wih other functons.

`plot_aggregate_biomass` is a little different. i dont believe we want anything else to be returned other than the plot

**Comment by BBeltz1** [comment]
thought so. thanks for verifying, i'll mark those as intended and complete.

**Comment by andybeet** [comment]
`plot_habs` is the same as `plot_gsi` just reversed
