### ISSUE TITLE
Revamp intro to catalog

### ISSUE THREAD

**Issue by slucey** [NOAA-EDAB/catalog#3]

**Comment by slucey** [comment]
Intro page needs to outline the purpose of the catalog, links to methods (tech doc), data (ecodata), and reports (SOEs).  Need map of the area and maps of the EPUs.

**Comment by slucey** [comment]
Should include a description of how to install/use `ecodata`.

**Comment by slucey** [comment]
Include reference to `tech-doc:TrendAnalysis.Rmd`

**Comment by slucey** [comment]
Include a link to an issue template for a data request.

**Comment by khyde** [comment]
Should also think about the organization of the catalog (alphabetical, SOE order, major groupings) and explain that in the intro.
