### ISSUE TITLE
Catalog reorganization

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/catalog#34]
Need to remove dependencies, especially `renv`

Objectives:

- [x] Description file needs to not have the long list of Depends

- [x] See Andy's fork for corrections to [bookdown.yaml](https://github.com/andybeet/catalog/blob/master/.github/workflows/bookdown.yaml) workflow

- [x] All existing Rmds in chapters should have visualization chunks disabled:
    - [x] remove ``` at top and bottom
    - [x] comment out beginning at #{r, code=readlines.... etc

- [x] Then start to edit each Rmd to bring in new plot functions

**Comment by andybeet** [comment]
Since the Rmds have a completely new structure i think we will just "archive" the Rmds and start fresh. For those rmds in which there are no new submissions we will just cut and paste approriate content from the archived rmd into the new template
