### ISSUE TITLE
[Submission]: Paralytic Shellfish Poisoning in Gulf of Maine

### ISSUE THREAD

**Issue by BBeltz1** [NOAA-EDAB/catalog#68]
### Primary Contact

david.moe.nelson@noaa.gov

### Data Name (This will be the displayed title in Catalog)

Paralytic Shellfish Poisoning in Gulf of Maine

### Indicator Name (as exists in ecodata)

habs_psp

### Family (Which group is this indicator associated with?)

- [ ] Oceanographic
- [ ] Habitat
- [X] Lower trophic levels
- [ ] Megafauna
- [ ] Social
- [ ] Economic

### Data Description

These data represent the presence of PSP toxins in blue mussels at coastal sites in the Gulf of Maine (MA, NH, ME), and shellfishery closures (MA).

### Introduction to Indicator (Please explain your indicator)

These data represent the presence of PSP toxins in blue mussels (Mytilis edulis) sampled at coastal sites in Massachusetts (1972-2022), New Hampshire (2000-2022), and Maine (2005 to 2019). Results are summarized on an annual basis for each state. Variables include total number of samples, number of samples above and below a designated threshold (44ug STX equivalent / 100g tissue), and percentage of samples above the threshold. These data were provided by Yizhen Li, NOAA/NOS NCCOS Stressor Detection and Impacts Division, HAB Forecasting Branch, Silver Spring, MD. Original data for Maine were collected by Maine Department of Marine Resources, which tests coastal shellfish areas for biotoxins weekly, annually beginning in March and going through October or later when necessary. Original data for New Hampshire were collected by NH Department of Environmental Services, and original data for Massachusetts were collected by Massachusetts Division of Marine Fisheries.

### Key Results and Visualization

A line graph depicts the percentage of samples that exceed the designated threshold (44ug STX equivalent / 100g tissue), in the samples that had some level of STX detected. The percentages may be affected by protocols on where and when to sample – e.g. sampling may be more intense during bloom events, and protocols may differ between the three states (MA, NH, ME).
A three-tier column graph illustrates three different metrics of shellfish bed closures in Massachusetts waters due to PSP, 1990-2022. Annual metrics include number of sites closed, mean number of days closed per site, and total closed area (acres). Bloom events in the early 1990s, 2005, and 2009 are evident in the closure metrics.

### Implications

Alexandrium bloom events in the Gulf of Maine can result in Paralytic Shellfish Poisoning (PSP) toxins accumulating in shellfish and other species. Bloom events and shellfishery closures usually occur somewhere in any given year, but vary greatly between years and among local areas. The presence of PSP toxins in shellfish, and shellfishery closures have been used as metrics for assessing the severity of PSP outbreaks (Kleindinst et al. 2014). Economic impacts to inshore shellfisheries (mussels, softshell clams, quahogs) can be substantial (Jin and Hoagland 2008).

### Spatial Scale

Results are based on data from individual sites in the Gulf of Maine, aggregated by year and state (MA, NH, ME).

### Temporal Scale

Results are aggregated by year.

### Synthesis Theme

- [ ] Multiple System Drivers
- [X] Regime Shifts
- [ ] Ecosystem Reorganization

### Define Variables

1) Year; Definition: calendar year; Units: yyyy.
2) Name: State; Definition: MA, NH, or ME ; Units: categories.
3) Name: N_Rows; Definition: Number of sample events represented; Units: integer. 
4) Name: PSP_Exceed_Threshold_Pct; Definition: Percentage of samples exceeding PSP threshold; Units: decimal number, 0-100.

### Indicator Category

- [X] Published Methods
- [ ] Extensive analysis, not yet published
- [X] Syntheses of published information
- [X] Database pull
- [ ] Database pull with analysis
- [ ] Other

### Data Contributors

Yizhen Li, NOAA/NOS NCCOS Stressor Detection and Impacts Division, HAB Forecasting Branch, Silver Spring, MD.

### Point(s) of Contact

Moe Nelson (david.moe.nelson@noaa.gov)

### Affiliation

NEFSC

### Public Availability

Source data are NOT publicly available.

### Accessibility and Constraints

Data as aggregated are not publicly available. Data can be acquired upon request.

**Comment by andybeet** [comment]
combined content into HAB submission
