### ISSUE TITLE
Catalog page title, heading, and other edits: running list

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/catalog#81]
Across all pages

- [x] Correct typo in first section heading "Indroduction to Indicator"
- [x] See if we can only show checked categories in catalog pages where checkboxes are used in issues

Individual pages

- [x] Rename Commercial Revenue --> Commercial Landings and Revenue
- [x] Add text from [Commercial Landings](https://github.com/NOAA-EDAB/catalog/issues/53) submission to renamed Commercial Landings and Revenue page
- [x] Commercial Landings and Revenue should be in the "Economic & Social" category
- [x] Rename Forage Fish --> Forage Fish Index
- [x] Stock Status page is only plotting Mid plot, needs NE plot added
- [x] Aggregate Survey Biomass: Add table of species in each group ([code](https://github.com/NOAA-EDAB/SOE-MAFMC/blob/8badb9708277881e4b197d00fd66c82bdd5e0439/SOE-MAFMC-2024.Rmd#L1039-L1072) from MId SOE). Created a `plot_species_groupings` function. 
- [x] Right Whale Abundance only needs one set of plots, they are coastwide

**Comment by andybeet** [comment]
stock status page will need to be manually edited to add NE plot. The reason is because there is no EPU field in this data set. it is plotted by management council. This format is unlike any of the other datasets so it can not be automated without a hack
