### ISSUE TITLE
Bottom temp - seasonal gridded

### ISSUE THREAD

**Issue by khyde** [NOAA-EDAB/catalog#86]
There are two bottom temperature - seasonal gridded chapters that seem redundant.  27 has the data plots and 28 has the seasonal maps.  If possible, I would suggest merging them and adding the seasonal bottom temperature anomaly maps to this chapter as well.

**Comment by andybeet** [comment]
You are right. the `bottom_temp_glorys` was made in error. It has been removed and the catalog will reflect this in a few minutes.
The anomaly data is located in a different dataset (`bottom_temp_comp`), so it has its own page. We are considereing renaming some of these datasets after this cycle

**Comment by khyde** [comment]
I see the change in the catalog title, but I don't see the BT anomaly maps.  Do we have those?

**Comment by jcaracappa1** [comment]
We don't have BT anomaly maps. I didn't calculate anomalies on the seasonal gridded data, but I can add those for next year

**Comment by khyde** [comment]
OK, I thought we had them in the past, but now that I think about it, we didn't include them because we didn't trust the non-GLORYS data.
