### ISSUE TITLE
Marine heatwaves

### ISSUE THREAD

**Issue by khyde** [NOAA-EDAB/catalog#88]
I noticed that the Marine Heatwave - Surface has the surface and bottom intensity plots, while the Marine Heatwave - Bottom has the surface and bottom annual plots.  The text is essentially the same, but it would make sense to me to merge the two, with the annual plots on top because I think those are the most useful.  If you want to keep them separate, then the chapter titles need to be corrected.

**Comment by BBeltz1** [comment]
marine heatwaves were originally merged as one page, but it was requested that we split them into 'surface' and 'bottom'. what you're seeing now is the intermediary stage, where they haven't quite been finished. the most recent plan was to have a 'surface' page with the surface intensity and annual plots and a separate 'bottom' page with the bottom intensity and annual plots. i'm open to hearing thoughts on this @sgaichas @jcaracappa1 before we proceed with either route.

**Comment by jcaracappa1** [comment]
If the methods are actually the same then I would say merge them. I thought there were different criteria used to define bottom heatwaves though
